[features]
seeds = false
skip-lint = false
[programs.localnet]
smart_contract = "DRdBSPLQ1bhycHEEyrQujdosvFM45jCUNYua5YzBh8ev"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jada/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
