import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Button, Col, Layout, Row } from "antd";
import NextLink from "next/link";

import { Header } from "components/Header";
import { useMediaQuery } from "react-responsive";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const isTabletOrMobile = useMediaQuery({ query: "(max-width: 992px)" });
  return (
    <>
      <Head>
        <title>Time of Life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Layout>
        <Header />
        <main>
          <Row
            style={{
              background: " white",
              margin: "auto",
              padding: "5px 30px",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Col xs={24} lg={12}>
              <h1
                style={{
                  fontSize: "50px",
                }}
              >
                Virtual health for you.
              </h1>

              <p
                style={{
                  color: "#7D7987",
                  fontSize: "27px",
                  fontWeight: "500",
                  lineHeight: "40px",
                }}
              >
                Time of Life provides progressive, and affordable healthcare. We
                think for you, we care about you. Connect with your wallet,
                create and hold your health information in blockchain
                technology, print out as QR code and turn your time to life.
              </p>

              <NextLink href="/account">
                <Button type="primary" size="large">
                  Create Account
                </Button>
              </NextLink>
            </Col>

            <Col
              xs={24}
              lg={9}
              style={{
                textAlign: "center",
                marginTop: isTabletOrMobile ? "20px" : "0px",
              }}
            >
              <img src="/banner.jpg" width="100%" height="auto" />
            </Col>
          </Row>
        </main>
      </Layout>
    </>
  );
}
